name: Translator Service Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'translator-service/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'translator-service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        working-directory: ./translator-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mock
          
      - name: Run tests
        working-directory: ./translator-service
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest test/